name: Playwright Tests in Docker

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: '30 19 * * *'  # 7:30 am NZT (UTC+12)

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Cache node_modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

      - name: Install npm dependencies
        run: npm ci

#      Disable this step when the "Run Playwright tests in Docker" step is enabled/required again and "CI: true" not used!
#      - name: Install Playwright browsers
#        run: npx playwright install --with-deps

      - name: Run Playwright tests in Docker
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/work \
            -w /work \
            mcr.microsoft.com/playwright:v1.53.2-jammy \
            npx playwright test

#      - name: Run Playwright tests
#        run: npx playwright test
#        env:
#          CI: true

      - name: Upload Playwright HTML report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report
